version: '3'

services:
  hoops-staging:
    image: ghcr.io/techsoft3d/streaming-server:staging
    container_name: hoops-staging
    restart: unless-stopped
    ports:
      - "11183:11183"
      - "11035-11070:11035-11070"
    volumes:
      - "./patches/server_config.js:/opt/hoops_communicator/quick_start/server_config.js"
      - "./patches/Utils.js:/opt/hoops_communicator/server/node/lib/Utils.js"
      - "./models:/opt/hoops_communicator/models"
      - "./hoops_license.txt:/opt/hoops_communicator/hoops_license.txt"
    environment:
      - HOST_IP=${HOST_IP}

  file-server-staging:
    image: ghcr.io/techsoft3d/node-server:staging
    container_name: file-server-staging
    restart: unless-stopped
    ports:
      - "3001:3001"  #change to whatever port you want files to be served from, but default is 3000
    environment:
      - PORT=3001  # This sets the PORT dynamically
    volumes:
      - ./public-staging:/app/public  # Mounts local "public" folder into the container
    depends_on:
      - hoops-staging

  # proxy-server-staging:
  #   image: ghcr.io/techsoft3d/proxy-server:latest  
  #   container_name: proxy-server-staging
  #   restart: unless-stopped
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - hoops-staging